# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'add_config.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_addConfig(object):
    def setupUi(self, addConfig):
        addConfig.setObjectName("addConfig")
        addConfig.resize(300, 300)
        self.widget = QtWidgets.QWidget(addConfig)
        self.widget.setGeometry(QtCore.QRect(20, 40, 251, 221))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setTabletTracking(False)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 0, 1, 1)
        self.configName = QtWidgets.QLineEdit(self.widget)
        self.configName.setTabletTracking(False)
        self.configName.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.configName.setText("")
        self.configName.setObjectName("configName")
        self.gridLayout.addWidget(self.configName, 0, 1, 1, 2)
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setTabletTracking(False)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.usernamEdit = QtWidgets.QLineEdit(self.widget)
        self.usernamEdit.setTabletTracking(False)
        self.usernamEdit.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.usernamEdit.setText("")
        self.usernamEdit.setObjectName("usernamEdit")
        self.gridLayout.addWidget(self.usernamEdit, 1, 1, 1, 2)
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setTabletTracking(False)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.passwordEdit = QtWidgets.QLineEdit(self.widget)
        self.passwordEdit.setTabletTracking(False)
        self.passwordEdit.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.passwordEdit.setText("")
        self.passwordEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.passwordEdit.setObjectName("passwordEdit")
        self.gridLayout.addWidget(self.passwordEdit, 2, 1, 1, 2)
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setTabletTracking(False)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 3, 0, 1, 1)
        self.ipEdit = QtWidgets.QLineEdit(self.widget)
        self.ipEdit.setTabletTracking(False)
        self.ipEdit.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.ipEdit.setText("")
        self.ipEdit.setObjectName("ipEdit")
        self.gridLayout.addWidget(self.ipEdit, 3, 1, 1, 2)
        self.pushButton = QtWidgets.QPushButton(self.widget)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 4, 0, 1, 2)
        self.pushButton_2 = QtWidgets.QPushButton(self.widget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 4, 2, 1, 1)

        self.retranslateUi(addConfig)
        QtCore.QMetaObject.connectSlotsByName(addConfig)

    def retranslateUi(self, addConfig):
        _translate = QtCore.QCoreApplication.translate
        addConfig.setWindowTitle(_translate("addConfig", "添加设备"))
        self.label_4.setText(_translate("addConfig", "配置名："))
        self.configName.setPlaceholderText(_translate("addConfig", "请输入配置名称"))
        self.label.setText(_translate("addConfig", "用户名："))
        self.usernamEdit.setPlaceholderText(_translate("addConfig", "请输入终端用户名"))
        self.label_2.setText(_translate("addConfig", "密  码："))
        self.passwordEdit.setPlaceholderText(_translate("addConfig", "请输入终端密码"))
        self.label_3.setText(_translate("addConfig", "IP地址："))
        self.ipEdit.setPlaceholderText(_translate("addConfig", "请输入终端地址:端口"))
        self.pushButton.setText(_translate("addConfig", "确认"))
        self.pushButton_2.setText(_translate("addConfig", "取消"))
